services:
  py:
    build: ./py
    env_file:
      - ./.env
    privileged: true
    volumes:
      - ./shared_data:/data
    restart: no
  wss:
    build: ./wss
    env_file:
      - ./.env
    ports:
      - "${WSS_PORT}:${WSS_PORT}"
    volumes:
      - ./shared_data:/data
    restart: no
  next:
    build: ./app
    env_file:
      - ./.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./shared_data:/data
    restart: no